name: Setup OpenFOAM
description: Set up a specific version of OpenFOAM
inputs:
  openfoam-version:
    description: Version of OpenFOAM to set up
  cache:
    description: Whether to cache the OpenFOAM installation for future runs
    default: true
branding:
  icon: grid
  color: blue
runs:
  using: "composite"
  steps:
    - name: Prepare
      id: prep
      run: |
        if [ $(uname) == "Darwin" ]; then
          echo "openfoam-etc=/Applications/OpenFOAM-v${{ inputs.openfoam-version }}.app/Contents/Resources/etc" >> "$GITHUB_OUTPUT"
        elif [ ${{ inputs.openfoam-version }} -lt 1000 ]; then
          which wget && which add-apt-repository || echo "apt-packages-pre=wget software-properties-common" >> $GITHUB_OUTPUT
          echo "apt-packages=openfoam${{ inputs.openfoam-version }}" >> $GITHUB_OUTPUT
          echo "openfoam-etc=/opt/openfoam${{ inputs.openfoam-version }}/etc" >> "$GITHUB_OUTPUT"
        else
          which wget || echo "apt-packages-pre=wget gnupg" >> $GITHUB_OUTPUT
          echo "apt-packages=openfoam${{ inputs.openfoam-version }}-default" >> $GITHUB_OUTPUT
          echo "openfoam-etc=/usr/lib/openfoam/openfoam${{ inputs.openfoam-version }}/etc" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Install prerequisites
      if: steps.prep.outputs.apt-packages-pre
      uses: gerlero/apt-install@v1
      with:
        packages: ${{ steps.prep.outputs.apt-packages-pre }}
        cache: ${{ inputs.cache && inputs.cache != 'false' }}
    - name: Add OpenFOAM APT repository (openfoam.org)
      if: steps.prep.outputs.apt-packages && inputs.openfoam-version < 1000
      run: |
        sudo() {
          if [ $(id -u) -eq 0 ]; then
            "$@"
          else
            command sudo "$@"
          fi
        }

        sudo wget -O /etc/apt/trusted.gpg.d/openfoam.asc https://dl.openfoam.org/gpg.key
        sudo add-apt-repository http://dl.openfoam.org/ubuntu
      shell: bash
    - name: Add OpenFOAM APT repository (openfoam.com)
      if: steps.prep.outputs.apt-packages && inputs.openfoam-version >= 1000
      run: |
        sudo() {
          if [ $(id -u) -eq 0 ]; then
            "$@"
          else
            command sudo "$@"
          fi
        }

        wget -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
      shell: bash
    - name: Install OpenFOAM on Linux
      if: steps.prep.outputs.apt-packages
      uses: gerlero/apt-install@v1
      with:
        packages: ${{ steps.prep.outputs.apt-packages }}
        install-recommends: false
        update: ${{ inputs.openfoam-version < 1000 }}
        cache: ${{ inputs.cache && inputs.cache != 'false' }}
    - name: Get OS version
      if: runner.os == 'macOS' && inputs.cache && inputs.cache != 'false'
      id: os-version
      uses: sersoft-gmbh/os-version-action@v3
    - name: Cache OpenFOAM on macOS
      if: runner.os == 'macOS' && inputs.cache && inputs.cache != 'false'
      id: cache-macos
      uses: actions/cache@v4
      with:
        key: setup-openfoam-${{ inputs.openfoam-version }}-${{ runner.os }}-${{ steps.os-version.outputs.version }}-${{ runner.arch }}
        path: /Applications/OpenFOAM-v${{ inputs.openfoam-version }}.app
    - name: Install OpenFOAM on macOS
      if: runner.os == 'macOS' && steps.cache-macos.outputs.cache-hit != 'true'
      run: |
        brew install --no-quarantine gerlero/openfoam/openfoam@${{ inputs.openfoam-version }}
      shell: bash
    - name: Activate OpenFOAM for future steps
      run: |
        OLD_PATH="$PATH"
        source "${{ steps.prep.outputs.openfoam-etc }}/bashrc" || true

        for var in "${!WM_@}"; do
          echo "$var=${!var}" >> "$GITHUB_ENV"
        done

        for var in "${!FOAM_@}"; do
          echo "$var=${!var}" >> "$GITHUB_ENV"
        done

        echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

        echo "${PATH/%:$OLD_PATH}" >> "$GITHUB_PATH"
      shell: bash
    - name: Add openfoam command to PATH
      if: inputs.openfoam-version >= 1000
      run: |
        mkdir -p ~/.setup-openfoam/bin
        ln -s "${{ steps.prep.outputs.openfoam-etc }}/openfoam" ~/.setup-openfoam/bin/openfoam${{ inputs.openfoam-version }}
        ln -s "${{ steps.prep.outputs.openfoam-etc }}/openfoam" ~/.setup-openfoam/bin/openfoam
        echo ~/.setup-openfoam/bin >> "$GITHUB_PATH"
      shell: bash
